### ISSUE TITLE
The logo illustration does not follow licence

### ISSUE THREAD

**Issue by tenntenn** [itsksaurabh/go-corona#17]
The logo of your library does not follow licences of below.

* [The Go Gopher](https://blog.golang.org/gopher)
* [My illustration](https://github.com/tenntenn/gopher-stickers)
* [The logo of Go](https://blog.golang.org/go-brand)

Could you fix the logo to follow the licences.

**Comment by itsksaurabh** [comment]
@tenntenn sure. I haven't done it before for a logo/art. could you please guide me on how to do it properly? Thanks!

**Comment by tenntenn** [comment]
Could you confirm the licences and the guideline? You can read them via above links.

**Comment by tenntenn** [comment]
Thank you for fixing but I think the logo does not follow the guideline of Go's logo yet.
https://golang.org/s/brandbook
![Screenshot_20200323-083726](https://user-images.githubusercontent.com/796820/77265993-974bf380-6ce1-11ea-9848-37b45501c26c.png)
