### ISSUE TITLE
Cannot get latest version: module contains a go.mod file, so module path should be github.com/itsksaurabh/go-corona/v2

### ISSUE THREAD

**Issue by KateGo520** [itsksaurabh/go-corona#26]
## Background
The `github.com/itsksaurabh/go-corona` uses [Go modules](https://github.com/golang/go/wiki/Modules) and the current release version is `v2`. And it’s module path is `"github.com/itsksaurabh/go-corona"`, instead of `"github.com/itsksaurabh/go-corona/v2"`. It must comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. Quoting the specification:
> A package that has opted in to modules _must_ include the major version in the import path to import any v2+ modules
> To preserve import compatibility, the go command requires that modules with major version v2 or later use a module path with that major version as the final element. For example, version v2.0.0 of _example.com/m_ must instead use module path _example.com/m/v2_.
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

## Steps to Reproduce
GO111MODULE=on, run `go get` targeting any version >= v2.0.0 of the `itsksaurabh/go-corona`:
```
$ go get github.com/itsksaurabh/go-corona@v2.0.0
go: finding github.com/itsksaurabh/go-corona v2.0.0
go: finding github.com/itsksaurabh/go-corona v2.0.0
go get github.com/itsksaurabh/go-corona@v2.0.0: github.com/itsksaurabh/go-corona@v2.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```
run `go get github.com/itsksaurabh/go-corona`, the version will stuck in v1.0.3:
```
$go get github.com/itsksaurabh/go-corona
go: downloading github.com/itsksaurabh/go-corona v1.0.3
go: github.com/itsksaurabh/go-corona upgrade => v1.0.3
```
SO anyone using Go modules will not be able to easily use any newer version of `itsksaurabh/go-corona`.

### 1. Kill the go.mod files, rolling back to GOPATH.
This would push them back to not being managed by Go modules (instead of incorrectly using Go modules).
Ensure compatibility for downstream module-aware projects and module-unaware projects projects

### 2. Fix module path to strictly follow SIV rules.
Patch the `go.mod` file to declare the module path as `github.com/itsksaurabh/go-corona/v2` as [per the specs](https://github.com/golang/go/wiki/Modules#semantic-import-versioning). And adjust all internal imports.
The downstream projects might be negatively affected in their building if they are module-unaware (Go versions older than 1.9.7 and 1.10.3; Or use third-party dependency management tools, such as: Dep, glide,govendor…).

If you don't want to break the above repos. This method can provides better backwards-compatibility.
Release a v2 or higher module through the major subdirectory strategy: Create a new v2 `subdirectory` (github.com/itsksaurabh/go-corona/v2) and place a new go.mod file in that subdirectory. The `module path` must end with `/v2`. Copy or move the code into the v2 subdirectory. Update `import statements` within the module to also use `/v2` (import "github.com/itsksaurabh/go-corona/v2/…"). Tag the release with `v2.x.y`.

### 3.  Major version bump / repository change
Leave `v2` as a dead version and bump to v3 with the path changes.

### 4.  Suggest your downstream module users use hash instead of a version tag.
If the standard rule of go modules conflicts with your development mode. Or not intended to be used as a library and does not make any guarantees about the API. So you can’t comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. 
Regardless, since it's against one of the design choices of Go, it'll be a bit of a hack. Instead of `go get github.com/itsksaurabh/go-corona@version-tag`, module users need to use this following way to get the `itsksaurabh/go-corona`:
   (1) Search for the `tag` you want (in browser)
   (2) Get the `commit hash` for the `tag` you want
   (3) Run `go get github.com/itsksaurabh/go-corona@commit-hash`
   (4) Edit the go.mod file to put a comment about which version you actually used
This will make it difficult for module users to get and upgrade `itsksaurabh/go-corona`.

**[*]** You can see who will be affected here: [3 module users, e.g., itsksaurabh/go-wazirx, dickysuryos/botWhatsappCovid, RTradeLtd/ipcoronafs]
https://github.com/search?q=itsksaurabh%2Fgo-corona+filename%3Ago.mod&type=Code

## Summary
You can make a choice to fix DM issues by balancing your own development schedules/mode against the affects on the downstream projects.

For this issue, `Solution 2` can maximize your benefits and with minimal impacts to your downstream projects the ecosystem. 

## References
* https://github.com/golang/go/wiki/Modules#semantic-import-versioning
* https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
* https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by KateGo520** [comment]
@itsksaurabh @turnkey-commerce  Could you help me review this issue? Thx :p

**Comment by turnkey-commerce** [comment]
@KateGo520 I agree that going to a 3.0 version would be the path of least resistance, even though the major version change seems unnecessary if there are not breaking changes according to Semver, but perhaps 2.0 => 3.0 would be considered an "un-breaking change" since it changes the behavior to the proper intended use of modules and is part of the developer UX interface.  I like the second approach of the V3 subdirectory since it has the most backward compatibility.

**Comment by turnkey-commerce** [comment]
Another thought is doing a patch as 2.0.1 with just the module name approach without the directory changes as the least amount of change.  Some other libraries like gorp have done that approach.

**Comment by KateGo520** [comment]
@turnkey-commerce  Thanks for your feedback and help.

**Comment by KateGo520** [comment]
Close this issue via commit [57ae9b6](https://github.com/itsksaurabh/go-corona/pull/27/commits/57ae9b60656ec5824f20c603b21e5ba53b38d726)
